# Generated by Django 4.2.4 on 2023-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity ordered'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='quantity in stock'),
        ),
    ]
